### ISSUE TITLE
gtechmonitor ui2.awin.com results in this link is inactive

### ISSUE THREAD

**Issue by fogoat** [NopeCHALLC/nopecha-extension#113]
I assume there's an affiliate link set up for certain domains that nopecha is redirecting from. That affiliate link seems to be inactive. Instead of taking me to the destination site, the redirect stops and says "This link is inactive".

![hp-gtechmonitor](https://github.com/user-attachments/assets/6861e367-3f63-42cb-8427-3b647de77385)

**Comment by NopeCHALLC** [comment]
We do not have affiliate link redirects in our extension. You are using another extension that is using this shady practice.
