### ISSUE TITLE
Chrome extension does not import settings in Playwright (edited)

### ISSUE THREAD

**Issue by galaczi** [NopeCHALLC/nopecha-extension#14]
I reported this issue a while ago on Discord. I am trying to use the Chrome extension in Playwright in incognito mode. I am able to set up and enable the plugin. Itopens the hCaptcha challenge, but then nothing happens.

If I click the extension in Chrome, I see that my balance is not showing, nor my API key. Looks like the extension cannot make a connection to your service.

Checking the console, I only see this message:

`api.js?_=1682260967771:3 Only one captcha is permitted per parent container.`

I create a reproduction if needed.

Edit: It's not an incognito issue, I cannot import my settings without incognito either. The URL is visited, the extension is enabled, but the settings are not imported.

**Comment by Jaewan-Yun** [comment]
Version 0.4 allows you to set the API key in manifest.json
While it's officially not released, you may download through our Discord in a channel named `V0.4 BETA download`
[Discord Invite URL](https://nopecha.com/discord)
