### ISSUE TITLE
Ip detected as VPN/Proxy

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [NopeCHALLC/nopecha-extension#19]
![image](https://github.com/NopeCHALLC/nopecha-extension/assets/7016954/9e2839d9-e82c-44da-b686-4cb762d9c399)

I sometimes uses VPN on my computer, but when I took the screen (from developper panel of the extension popup ) I wasn't using any VPN or proxy

**Comment by devbytemehedi** [comment]
I almost never use vpn but i had used vpn before installing this extension but after installing i didn't use vpn but in the extension it says Your IP is ineligible for free credits.

**Your IP is ineligible for free credits. Purchase a key to use with VPN/proxy.**
![BKbLSdQd6u](https://github.com/NopeCHALLC/nopecha-extension/assets/89072438/3947c60f-729c-4693-8974-5ac46ef62186)

**Comment by ErdbeerbaerLP** [comment]
Same here

Not using an VPN

**Comment by ToasterUwU** [comment]
Have not used a VPN or Proxy, still have that same error message. 

I assume its because I have a dynamic IP (since that's the only option my ISP has), but dynamic residential IP doesn't make this a Proxy or a VPN.

**Comment by Rukhazon** [comment]
Hello,
I am connected through a small ISP, and the extension is saying that I am using a VPN (which is not the case).
My IP is static. Could you authorize it?
The IP address is 176.118.175.151
Thank you.

**Comment by Apocalypsing** [comment]
Same issue on my end here in Australia. My ISP is Launtel (AS number of 134697) which is a business-oriented ISP, from which I have a statically-assigned IPv4 address from them, in the subnet of `203.12.14.0/24`. I also have IPv6 through Launtel, in their subnet that is `2404:e80:9000::/36`.

**Comment by NopeCHALLC** [comment]
@Apocalypsing
> Same issue on my end here in Australia. My ISP is Launtel (AS number of 134697) which is a business-oriented ISP, from which I have a statically-assigned IPv4 address from them, in the subnet of `203.12.14.0/24`. I also have IPv6 through Launtel, in their subnet that is `2404:e80:9000::/36`.

We cannot find any record of `AS 134697`, `203.12.14.0/24`, and `2404:e80:9000::/36` in our list of banned addresses. Are you receiving a `Banned IP` message or unable to connect to `api.nopecha.com`?

**Comment by anirudhp06** [comment]
I have never used VPN/proxy on desktop still receiving error "Your IP is ineligible for free credits.
Purchase a key to use with VPN/proxy."
Should i mention my IP address here to unlist? My IP address will keep changing whenever i restart my router...

**Comment by Jaewan-Yun** [comment]
@anirudhp06  

> I have never used VPN/proxy on desktop still receiving error "Your IP is ineligible for free credits. Purchase a key to use with VPN/proxy." Should i mention my IP address here to unlist? My IP address will keep changing whenever i restart my router...

I totally get where you're coming from, it's frustrating when you're just trying to use a service and encounter issues like this. You can either drop your IP address here or you can shoot us a message through our Discord's ticketing system. We'll get you sorted out.

These checks are in place to prevent abusers from gaming our system. Our detection methods aren't bulletproof, and it may flag legitimate users on dynamic IP. However, without these checks, we wouldn't be able to offer the service for free.

Thanks for your understanding, and sorry for the hassle.

**Comment by Apocalypsing** [comment]
> @Apocalypsing
> 
> > Same issue on my end here in Australia. My ISP is Launtel (AS number of 134697) which is a business-oriented ISP, from which I have a statically-assigned IPv4 address from them, in the subnet of `203.12.14.0/24`. I also have IPv6 through Launtel, in their subnet that is `2404:e80:9000::/36`.
> 
> We cannot find any record of `AS 134697`, `203.12.14.0/24`, and `2404:e80:9000::/36` in our list of banned addresses. Are you receiving a `Banned IP` message or unable to connect to `api.nopecha.com`?

Nothing like "banned IP", no. I have been seeing the exact same message that @thecodermehedi's screenshot is showing above; saying that my IP is not eleglible for free credits.

**Comment by hoanghiep1x0** [comment]
captcha lol

**Comment by kittenvr** [comment]
same issue
