### ISSUE TITLE
New hcaptcha support?

### ISSUE THREAD

**Issue by Luzivog** [NopeCHALLC/nopecha-extension#20]
When I try to solve hcaptchas I get this:
![image](https://github.com/NopeCHALLC/nopecha-extension/assets/57810766/8ed7c90d-24e3-4d18-9d98-181b827a263d)

Is it already possible to bypass them or is it simply not supported yet?

**Comment by edenriquez** [comment]
same captcha here, extension does not work even tho i have enough credits 
<img width="552" alt="image" src="https://github.com/NopeCHALLC/nopecha-extension/assets/26972091/98591301-bffb-4593-9e14-3d4ece42992d">

**Comment by RafaelGruhn** [comment]
Same problem here, any predictions on when it will be supported?

**Comment by NopeCHALLC** [comment]
This challenge has been solved for some time now. You may want to upgrade to the latest version for full compatibility.
Let me know if any of you are still having issues.
