### ISSUE TITLE
Chrome extension menu not visible

### ISSUE THREAD

**Issue by seidnerj** [NopeCHALLC/nopecha-extension#21]
<img width="534" alt="Screenshot 2023-09-18 at 14 18 13" src="https://github.com/NopeCHALLC/nopecha-extension/assets/4147381/9e80621c-3e47-430f-8b1b-355e3dc3573a">

Makes this unusable, please fix this.

**Comment by hackerdb** [comment]
same issues

**Comment by NopeCHALLC** [comment]
This issue has been resolved since the release of v0.4. Please update your clients if you have not yet done so.
