### ISSUE TITLE
/setup is deprecated, please use the automation build instead.

### ISSUE THREAD

**Issue by Andreito95** [NopeCHALLC/nopecha-extension#23]
Hello, i get this error after version 4 updates.
How to handle the extension activation on selenium chrome webdriver?

The only way is to edit the manifest.json file? Have you an example of code to edit it correctly?

Thank you!

**Comment by kamranayub** [comment]
Here is how I handle this:

1. Copy extension directory to temporary (build output) folder
2. Read `manifest.json`
3. If it does not have a key set, set from `env` variable

You can adjust it based on your needs. The key is that the original extension is stored as a zip/unzipped without committing the API key to Git.

**scripts/prepareNopechaExtension.mjs**

```ts
import path from "path";
import fs from "fs/promises";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const tempFolder = "dist";

await prepareNopechaExtension();

async function prepareNopechaExtension() {
  const extensionSourcePath = path.join(
    path.dirname(__filename),
    "..",
    "..",
    "nopecha"
  );
  const extensionDestPath = path.join(
    path.dirname(extensionSourcePath),
    tempFolder,
    "nopecha"
  );

  const extensionDestExists = !!(await fs
    .stat(extensionDestPath)
    .catch(() => null));

  if (!extensionDestExists) {
    await fs.mkdir(extensionDestPath, { recursive: true });
    await fs.cp(extensionSourcePath, extensionDestPath, { recursive: true });
  }

  const manifestFile = await fs.readFile(
    path.join(extensionDestPath, "manifest.json"),
    "utf-8"
  );

  if (!manifestFile) {
    throw new Error(
      "Could not find Nopecha manifest.json in: " + extensionDestPath
    );
  }

  const manifestJson = JSON.parse(manifestFile);

  if (!manifestJson["nopecha"]["key"]) {
    const key = process.env.NOPECHA_API_KEY;

    if (!key) {
      throw new Error(
        "Missing NOPECHA_API_KEY and manifest.json does not contain a key."
      );
    }

    manifestJson["nopecha"]["key"] = key;

    await fs.writeFile(
      path.join(extensionDestPath, "manifest.json"),
      JSON.stringify(manifestJson, null, 2)
    );
  }
}
```

```sh
node scripts/prepareNopechaExtension.mjs
```

**Comment by Jaewan-Yun** [comment]
We've marked this feature as deprecated, mainly because we've heard from some of our users about its unpredictable behavior, especially when network issues are involved. We'd love to make it more robust, but doing so would require adding extra security permissions to the extension. We believe that's not the best path forward, given that this feature addresses a rather niche use-case.

But don't worry, it's not on the chopping block for any upcoming releases. However, it's important to note that we won't be focusing on further updates or support for it anytime soon.

If you're looking for a way to pre-configure your extension settings, we've got you covered! We recommend you to switch to the automation build. This alternative lets you set your preferences directly within the `manifest.json` file. We've put together a detailed guide on how to do that in our [Extension Configuration Documentation](https://developers.nopecha.com/guides/extension_advanced/#automation-build).

**Comment by Andreito95** [comment]
@kamranayub @Jaewan-Yun 

I am following this guide:

![image](https://github.com/NopeCHALLC/nopecha-extension/assets/83916082/371b0a76-1c00-4c9a-9d6c-29731c0f2055)

But... i can't find the nopecha section when i open the manifest.json file...
This is my actual code


`# Download the latest unpacked NopeCHA extension.
                with open('nopecha.zip', 'wb') as f:
                    f.write(requests.get('https://nopecha.com/f/chrome.zip').content)
                with zipfile.ZipFile('nopecha.zip', 'r') as zip_ref:
                    zip_ref.extractall('nopecha')
                
                browser_options.add_argument(f"--load-extension={os.getcwd()}/nopecha")
                logger.debug("[Selenium] NopeCHA: Extension installed")`

I would like to add before "load extension" the "manifest.json" edit to put the "nopecha_key" into it
i can't find that key tho... i don't know why

I attach the zip file

[chrome.zip](https://github.com/NopeCHALLC/nopecha-extension/files/13125628/chrome.zip)

**Comment by Jaewan-Yun** [comment]
@Andreito95

The latest versions can be downloaded from the [GitHub release section of this repository](https://github.com/NopeCHALLC/nopecha-extension/releases).

If you want to set your settings via `manifest.json` over an exported URL, then choose `chromium_automation.zip` for Chromium-based browsers or `firefox_automation.zip` for Firefox. You will find the `manifest.json` that contains the `nopecha` section in these zip files. The [extension configuration guide](https://developers.nopecha.com/guides/extension_advanced/#automation-build) applies to both browser automation builds.

**Comment by Andreito95** [comment]
It's working flawlessly guys. It's working very, very well.
I appreciate your efforts.

I manage the download of the latest release each time I start a driver, using the response.json from 'api.github.com/repos.'
Then, I edit the manifest.json in the files extracted from the content of 'chromium_automation.zip.'

It works perfectly now. Thank you very much.

**Comment by Andreito95** [comment]
@Jaewan-Yun can you please delete this issue? i don't want to leave trace of this issue in this account.
please let me know
