### ISSUE TITLE
Is it still possible to solve Hcaptcha?

### ISSUE THREAD

**Issue by MatheusVCosta** [NopeCHALLC/nopecha-extension#42]
Hi Guys!

I'm developing a web-crawler and I need to solve an hCaptcha challenge, but I can't.
I tried using captcha solving services like 2Captcha, CapSolver and deathByCaptcha, but none of them worked.
Is it still possible today to crack captcha challenges using these services nowsday?
In specific the hCaptcha.

If somebody can help me with this, i needing so much solve a captcha.

**Comment by CuteistFox** [comment]
this is scam

**Comment by edimarmonteiro** [comment]
Ola pessoa, estou tentando resolver um HCaptcha através da biblioteca anti-captcha. Consigo quebrar o captcha, mas por algum motivo fica informando "Captcha não Informado!". Estou fazendo isso com TypeScript e Playwright.
Esse é o código:

**Código:**
async function solveHCaptcha(page: Page) {
  const iframeSelector = 'iframe[src]';
  await page.waitForSelector(iframeSelector);
  const hcaptcha = await page.$(iframeSelector);
  await waitingTime(7000);

  if (hcaptcha !== null) {
    const hcaptchaSrc = await hcaptcha.getAttribute("src");
    if (hcaptchaSrc !== null) {
      const siteKey = hcaptchaSrc.split('&')[10].split('=')[1];
      console.log('siteKey do if hcaptcha: ' + siteKey);

      const responseSelector = 'textarea[name="h-captcha-response"]';
      await page.waitForSelector(responseSelector);
      const hcaptchaResponse = await page.$(responseSelector);
      const isInvisible = false;
      const isEnterprise = false;
      antiCaptach.setAPIKey('--------------------------------');
      const setWebsiteKey = 'https://radar.serpro.gov.br/main.html#/cidadao'

      antiCaptach.setSoftId(0);
      await waitingTime(7000);
      try {
        const gresponse = await antiCaptach.solveHCaptchaProxyless(setWebsiteKey, siteKey, isInvisible, isEnterprise);
        console.log('g-response: ' + gresponse);
        if (hcaptchaResponse) {
          await hcaptchaResponse.fill(gresponse);
          console.log('Acabei de adicionar o valor do captcha');
        }
      } catch (error) {
        console.log('test received error ' + error);
      }
    }
  }
}

async function submitPage(page: Page){
  await page.getByText('Pesquisar').click();
}

**Image:**
![breakingHCaptcha](https://github.com/NopeCHALLC/nopecha-extension/assets/101994520/adac2918-e605-405d-a3f9-94a845490e96)


Serei muito grato se alguem conseguir me ajudar

**Comment by NopeCHALLC** [comment]
It takes time for our models to learn new hCaptcha challenges as they are added.

Please let us know if you notice that it's taking longer than a day for the recognition quality to improve.
