### ISSUE TITLE
Can't generate keys

### ISSUE THREAD

**Issue by seantek** [NopeCHALLC/nopecha-extension#45]
I am using NopeCHA for personal occasional use. Sometimes I create a key and use a few credits--but almost never the full amount of 200 credits.

Over the last few days, I get the error message: "You have generated a maximum number of free keys." I did not know there is any maximum--it is not disclosed. The only thing disclosed is that you can only generate a free key once every 24 hours, and you get 200 credits. If I knew there was some mysterious "maximum number" I would not have generated hardly any keys!

Please advise what this "maximum" number is and reset it for my account/other users' accounts. Thank you.

**Comment by j-w-yun** [comment]
The limit was removed.
