### ISSUE TITLE
Recaptcha broken not showing up (BUG)

### ISSUE THREAD

**Issue by GITHUBTRASHACCOUNT** [NopeCHALLC/nopecha-extension#49]
![image](https://github.com/NopeCHALLC/nopecha-extension/assets/115583890/0e3efca6-fa9c-425e-80b1-601adc78d858)
![image](https://github.com/NopeCHALLC/nopecha-extension/assets/115583890/1d9bd3d8-126a-4a75-92e3-0c5f65cf0a3a)

**Comment by j-w-yun** [comment]
The problem that you're seeing is unrelated to this project, as it is a symptom of your network / browser configuration. The most likely cause of this is that you are using a slow proxy / network connection which fails to load the resources from Google. Please check your network connection and let us know if the problem persists.

**Comment by arthurauffray** [comment]
I've got a similar issue, and the Nopecha extension causes it; the problem is non-existent while the extension is disabled.
It also occurs whether the extension is turned on or off from the popup.

Even on the nope cha demo page, the captchas don't load (a NET ERR too many redirects)
<img width="479" alt="Screenshot 2024-06-10 at 1 40 29 AM" src="https://github.com/NopeCHALLC/nopecha-extension/assets/51604173/efd7052f-4c1c-42aa-8e7f-33d102e20bd4">

This occurs on other websites, too, and the captcha boxes typically load this:
<img width="335" alt="Screenshot 2024-06-10 at 1 41 55 AM" src="https://github.com/NopeCHALLC/nopecha-extension/assets/51604173/18f663a5-44af-4b9c-8d5a-594bdc90c052">

But occasionally (or after staying on the page for a while they turn to this:
<img width="306" alt="Screenshot 2024-06-10 at 1 41 22 AM" src="https://github.com/NopeCHALLC/nopecha-extension/assets/51604173/364ab612-a306-4916-8a1f-27dd82795c7c">

**Comment by Le0Developer** [comment]
> @NopeCHALLC I've got a similar issue, and the Nopecha extension causes it; the problem is non-existent while the extension is disabled. It also occurs whether the extension is turned on or off from the popup.
> 
> Even on the nope cha demo page, the captchas don't load (a NET ERR too many redirects) <img alt="Screenshot 2024-06-10 at 1 40 29 AM" width="479" src="https://private-user-images.githubusercontent.com/51604173/337977792-efd7052f-4c1c-42aa-8e7f-33d102e20bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDU1MjcsIm5iZiI6MTcxODAwNTIyNywicGF0aCI6Ii81MTYwNDE3My8zMzc5Nzc3OTItZWZkNzA1MmYtNGMxYy00MmFhLThlN2YtMzNkMTAyZTIwYmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMTlmN2VkMzNhZjUxM2VmYjVjNDVhNDE5MGI1ZjZmZjAwNjg0MWQxNmE4Yjc2YmQxMzc0MmIxYjRkYmNhNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.88KEL9ZQoB1yh22AmNsVCT6XPo00_DNe6fLnQZT8NT8">
> 
> This occurs on other websites, too, and the captcha boxes typically load this: <img alt="Screenshot 2024-06-10 at 1 41 55 AM" width="335" src="https://private-user-images.githubusercontent.com/51604173/337977868-18f663a5-44af-4b9c-8d5a-594bdc90c052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDU1MjcsIm5iZiI6MTcxODAwNTIyNywicGF0aCI6Ii81MTYwNDE3My8zMzc5Nzc4NjgtMThmNjYzYTUtNDRhZi00YjljLThkNWEtNTk0YmRjOTBjMDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMjlhYzg3MGIwNzUxNDc4ZDJlOTBiYzE5OTg3MDkyZjQ0Y2QwMmU0MmI1NzBiOGM2M2JmN2RkMDZjNDVjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Mg0m9TSkflcqeV1B8F9-5z7hjetAt5AZsviJazq_8Y">
> 
> But occasionally (or after staying on the page for a while they turn to this: <img alt="Screenshot 2024-06-10 at 1 41 22 AM" width="306" src="https://private-user-images.githubusercontent.com/51604173/337977841-364ab612-a306-4916-8a1f-27dd82795c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDU1MjcsIm5iZiI6MTcxODAwNTIyNywicGF0aCI6Ii81MTYwNDE3My8zMzc5Nzc4NDEtMzY0YWI2MTItYTMwNi00OTE2LThhMWYtMjdkZDgyNzk1YzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZjdmOTI2MzU5ZTBmZGRlNmViNDE1NGU5ODE2ZTNmNTZhNjIyZWQxNjY3MTVlZDQxYTE1YmNlNzZjZDY2ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NtR2Sv9XZyG-92NHFGStG3rUj_Nt-K4UqwqjBDInnGA">

Disable the Buster extension.

**Comment by arthurauffray** [comment]
> Disable the Buster extension.

Ah, yes, this solved it for me; not sure if this occurs with a lot of users, maybe worth to put this somewhere. Do you have details on why having both extensions causes this?

Thanks!
