### ISSUE TITLE
Extension conflict

### ISSUE THREAD

**Issue by l-Nuril-l** [NopeCHALLC/nopecha-extension#52]
https://github.com/dessant/buster/issues/407#issuecomment-2159116449

**Comment by l-Nuril-l** [comment]
@j-w-yun The last 2 updates were not published in the Chrome Web Store.

**Comment by Le0Developer** [comment]
> @j-w-yun The last 2 updates were not published in the Chrome Web Store.

They were, but they need to be approved by Google which Takes time.

**Comment by j-w-yun** [comment]
> @j-w-yun The last 2 updates were not published in the Chrome Web Store.

Version 0.4.10 was submitted and awaiting feedback. The latest version (0.4.11) will need to wait until the prior one has completed the review process. Both will likely be published sometime this week.
