### ISSUE TITLE
 Your IP is ineligible for free credits. Purchase a key to use with VPN/proxy.

### ISSUE THREAD

**Issue by spidy2356** [NopeCHALLC/nopecha-extension#6]
i just install it in firefox and shows this, there are many reviews on firefox that says, they buy a key even after the same issue occur. so plz solve it and is it really paid extension???

**Comment by NopeCHALLC** [comment]
Thank you for reaching out. I understand that you've installed our extension and are experiencing some issues. I'm here to help you with that!

To use our extension on a proxy or VPN, you'll need to enter your API key in the Chrome/Firefox extension popup. You can find your API key by visiting [this page](https://nopecha.com/manage). Once you have your API key, please follow these steps:

1. Click on the extension icon in your Chrome/Firefox browser.
2. In the popup window, you'll see a field for entering your API (subscription) key.
3. Enter the API key that you retrieved from the Nopecha management page.
4. Press Enter to save

This should resolve the issue you're facing. If you encounter any issues or have further questions, please don't hesitate to reach out.

**Comment by NopeCHALLC** [comment]
For questions or issues related to billing, please contact us on [Discord](https://nopecha.com/discord).

**Comment by spidy2356** [comment]
> For questions or issues related to billing, please contact us on [Discord](https://nopecha.com/discord).

is the extension not free or not have any free version??

**Comment by NopeCHALLC** [comment]
You can access free credits on IP addresses that are not leased to a business entity.

**Comment by spidy2356** [comment]
@NopeCHALLC  I use wifi services for personal use....I don't know it is for business or not but I can't use it...it's shows the same problem that I issued

> You can access free credits on static IP addresses that are not leased to a business entity.

**Comment by spidy2356** [comment]
@NopeCHALLC I can't access discord server without a subscription key so I ask my question here
1. I got 200 credit from GitHub free key but will it reset after 24 hrs or need to redeem again when all my credits are finished?? Cause 200 credit are enough for me to continue upto 1 month.

2. Can I use one free key on more than one browser??

**Comment by bbaster** [comment]
@NopeCHALLC So a static IP is required to use this extension?

**Comment by spidy2356** [comment]
> @NopeCHALLC So a static IP is required to use this extension?
@NopeCHALLC  no.
