### ISSUE TITLE
speech recognition doesn't work in other languages than English

### ISSUE THREAD

**Issue by tobwen** [NopeCHALLC/nopecha-extension#61]
Some challenges, like AWS WAF are solved by translating the audio challenge from language to text. However, if the browser has Dutch as locale, for example, the captcha is also spoken in Dutch. However, NopeCHALLC only seems to recognize the English language.

**Comment by Le0Developer** [comment]
This is working as intended, we only support English at this time.  
Please change your browser language.

**Comment by tobwen** [comment]
> This is working as intended, we only support English at this time. Please change your browser language.

That will trigger the captcha immediately, since they're testing for ISP-location and browser language. How expensive would it be if you implemented the function?
