### ISSUE TITLE
Subscription Active, But Extension Not Working with Cloudflare CAPTCHA

### ISSUE THREAD

**Issue by Oldweedkeeper2** [NopeCHALLC/nopecha-extension#63]
Hello,

I recently purchased a subscription to NopeCHA and activated it. However, when attempting to bypass the Cloudflare CAPTCHA on stake.us, the extension does not function as expected, even though it is supposed to support this type of CAPTCHA. The attached screenshot shows that the subscription is active and the necessary options are enabled.

Steps to Reproduce the Issue:

    Activate the NopeCHA subscription.
    Ensure the extension is enabled and all necessary options are turned on.
    Navigate to stake.us.
    Attempt to pass the Cloudflare CAPTCHA.

Expected Behavior:
The extension should automatically solve the Cloudflare CAPTCHA, but it fails to do so.

Actual Behavior:
The extension does not perform its function, and I remain on the CAPTCHA verification page.

Screenshot:
![image](https://github.com/user-attachments/assets/0bb6f2a1-0bb3-4df9-9305-ecfdc11d6c01)
![image](https://github.com/user-attachments/assets/78fd8704-7211-4066-9814-7c81df081521)

Please assist in resolving this issue.

Thank you!

**Comment by Le0Developer** [comment]
1. Turnstile solver does not require a subscription
2. Turnstile solver is provided on a best-effort basis (it's free, see 1.)
3. Cloudflare patched our method multiple weeks ago and we haven't found a new one.
