### ISSUE TITLE
Not resolving Text captcha like this

### ISSUE THREAD

**Issue by MindMelodies** [NopeCHALLC/nopecha-extension#8]
Not resolving captcha like this

![get-code](https://user-images.githubusercontent.com/12814138/229311712-5f60d367-37ff-47e4-b029-69a703da1d4f.png)
![get-code (1)](https://user-images.githubusercontent.com/12814138/229311717-cd9187e1-478b-496c-9ede-0a8970b5e397.png)
![get-code (2)](https://user-images.githubusercontent.com/12814138/229311718-cefb582a-5c8d-4365-9635-f96b309e5d96.png)

**Comment by NopeCHALLC** [comment]
Do you have a source that we can scrape from? Please reach out to us on Discord. https://nopecha.com/discord
