### ISSUE TITLE
No Support at Discord

### ISSUE THREAD

**Issue by badplay** [NopeCHALLC/nopecha-extension#92]
i joined discord and got a roll starter with key but thats all nothing i can see inside the supportdiscord what should i do there is no ticket system

**Comment by NopeCHALLC** [comment]
Our team is currently upgrading our customer support system on Discord, which is temporarily inaccessible. Rest assured, we are working to restore the ticketing system as soon as possible.

In the meantime, we encourage you to consult our [Developer Guide](https://developers.nopecha.com/guides/) for detailed information and resources.

If you require further assistance, please feel free to reach out to us through this issue. We sincerely apologize for the inconvenience and appreciate your understanding and patience during this time.
