### ISSUE TITLE
Firefox Extension Broken

### ISSUE THREAD

**Issue by Insiderre** [NopeCHALLC/nopecha-extension#97]
![Screenshot_20241124_002029](https://github.com/user-attachments/assets/07c8d937-8f9a-4023-9d71-fb23e5670e59)
![Screenshot_20241124_002013](https://github.com/user-attachments/assets/99364551-0624-40db-9336-2c8057a68d19)

**Comment by nuttiness6179** [comment]
The Firefox extension is currently unsigned. You must install it using the  `Load Temporary Add-on` button on `about:debugging#/runtime/this-firefox`.

**Comment by Deswer60871** [comment]
firefox no have hcapcha solver
